### ISSUE TITLE
Space Shipe Kanban project 

### ISSUE THREAD

**Issue by ibr5500** [ibr5500/space-travelers-hub#25]
Hello there,

### We are a group of two (@GOlivierNation, and @ibr5500 ) developers. 

> - Here's the link to the project https://github.com/ibr5500/space-travelers-hub/

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] you are required to copy this [template](https://github.com/microverseinc/curriculum-react-redux/projects/1) which means that you should have four columns called "to do", "in progress", "in review" and "done"
- [ ] when removing all the cards for teams with 3 members you should be left with 17 cards, however, in your project, there are only 16 please add the missing card.
- [ ] @GOlivierNation has 11 points in total whereas @ibr5500 has 19 points in total which is too big of a difference in points please make sure all team members have more or less the same workload. 
- [ ] the cards for the group tasks should be assigned to a team member as well.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ibr5500** [comment]
Hello @mikethreels, we have made the changes.

**Comment by ibr5500** [comment]
Hello there,

### We are a group of two (@GOlivierNation, and @ibr5500 ) developers. 

> - Here's the link to the project https://github.com/ibr5500/space-travelers-hub/

This is the second submission.

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
